package com.example.ui.screens

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import androidx.compose.animation.*
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Info
import androidx.compose.material.icons.filled.Check
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material.icons.filled.Terminal
import androidx.compose.material.icons.filled.Lock
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DeploymentScreen(
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()

    // Form states for RouterOS script customization
    var poolName by remember { mutableStateOf("vpn-pool") }
    var ipRange by remember { mutableStateOf("10.0.10.10-10.0.10.50") }
    var localAddress by remember { mutableStateOf("10.0.10.1") }
    var ipsecSecret by remember { mutableStateOf("MySecureIpsecSecret") }
    var vpnUsername by remember { mutableStateOf("vpnuser") }
    var vpnPassword by remember { mutableStateOf("vpnpassword") }

    // Copying state
    var scriptCopied by remember { mutableStateOf(false) }

    // Real-time script generator
    val generatedScript = remember(poolName, ipRange, localAddress, ipsecSecret, vpnUsername, vpnPassword) {
        """
        # ----------------------------------------------------
        # MikroTik RouterOS - L2TP VPN Server Config Script
        # Generated by RouterControl App
        # ----------------------------------------------------

        # 1. Create IP pool for VPN clients
        /ip pool add name=$poolName ranges=$ipRange

        # 2. Create L2TP PPP profile with DNS servers
        /ppp profile add name=vpn-profile local-address=$localAddress remote-address=$poolName dns-server=8.8.8.8,1.1.1.1 use-encryption=yes

        # 3. Enable L2TP Server with IPSec Pre-Shared Key
        /interface l2tp-server server set enabled=yes use-ipsec=yes ipsec-secret="$ipsecSecret" default-profile=vpn-profile

        # 4. Create L2TP VPN User
        /ppp secret add name="$vpnUsername" password="$vpnPassword" service=l2tp profile=vpn-profile

        # 5. Allow L2TP & IPsec through firewall (Input chain)
        /ip firewall filter
        add chain=input protocol=udp dst-port=500 action=accept comment="L2TP IPsec IKE"
        add chain=input protocol=udp dst-port=1701 action=accept comment="L2TP Tunneling"
        add chain=input protocol=udp dst-port=4500 action=accept comment="L2TP IPsec NAT-T"
        add chain=input protocol=ipsec-esp action=accept comment="L2TP IPsec ESP"
        """.trimIndent()
    }

    Column(
        modifier = modifier
            .fillMaxSize()
            .background(MaterialTheme.colorScheme.background)
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp)
    ) {
        // Welcome Header
        Card(
            modifier = Modifier.fillMaxWidth(),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.primaryContainer)
        ) {
            Column(
                modifier = Modifier.padding(16.dp),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Icon(
                        imageVector = Icons.Default.Lock,
                        contentDescription = "Security Info",
                        tint = MaterialTheme.colorScheme.onPrimaryContainer
                    )
                    Text(
                        text = "Why L2TP VPN Tunnel?",
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.onPrimaryContainer
                    )
                }
                Text(
                    text = "Connecting via standard SSH over the internet is insecure and often blocked by firewalls or ISPs. " +
                            "By setting up an L2TP VPN server on your MikroTik router, your Android device establishes a fully encrypted tunnel. " +
                            "Once connected to the VPN, you can manage the router securely using its private local IP address (e.g. $localAddress).",
                    style = MaterialTheme.typography.bodyMedium,
                    color = MaterialTheme.colorScheme.onPrimaryContainer.copy(alpha = 0.85f)
                )
            }
        }

        // Configuration Form
        Card(
            modifier = Modifier.fillMaxWidth(),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
            border = androidx.compose.foundation.BorderStroke(1.dp, MaterialTheme.colorScheme.outline.copy(alpha = 0.15f))
        ) {
            Column(
                modifier = Modifier.padding(16.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Icon(
                        imageVector = Icons.Default.Settings,
                        contentDescription = "Configuration Params",
                        tint = MaterialTheme.colorScheme.primary
                    )
                    Text(
                        text = "Customize VPN Parameters",
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Bold
                    )
                }

                Divider(color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.08f))

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    OutlinedTextField(
                        value = poolName,
                        onValueChange = { poolName = it },
                        label = { Text("Pool Name") },
                        singleLine = true,
                        modifier = Modifier.weight(1f).testTag("l2tp_pool_name_input")
                    )

                    OutlinedTextField(
                        value = localAddress,
                        onValueChange = { localAddress = it },
                        label = { Text("Gateway/Local IP") },
                        singleLine = true,
                        modifier = Modifier.weight(1f).testTag("l2tp_local_address_input")
                    )
                }

                OutlinedTextField(
                    value = ipRange,
                    onValueChange = { ipRange = it },
                    label = { Text("Client IP Ranges") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth().testTag("l2tp_ip_range_input")
                )

                OutlinedTextField(
                    value = ipsecSecret,
                    onValueChange = { ipsecSecret = it },
                    label = { Text("IPsec Pre-Shared Secret") },
                    singleLine = true,
                    modifier = Modifier.fillMaxWidth().testTag("l2tp_ipsec_secret_input")
                )

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    OutlinedTextField(
                        value = vpnUsername,
                        onValueChange = { vpnUsername = it },
                        label = { Text("VPN Username") },
                        singleLine = true,
                        modifier = Modifier.weight(1f).testTag("l2tp_vpn_username_input")
                    )

                    OutlinedTextField(
                        value = vpnPassword,
                        onValueChange = { vpnPassword = it },
                        label = { Text("VPN Password") },
                        singleLine = true,
                        modifier = Modifier.weight(1f).testTag("l2tp_vpn_password_input")
                    )
                }
            }
        }

        // Generated Script Terminal Card
        Card(
            modifier = Modifier.fillMaxWidth(),
            colors = CardDefaults.cardColors(containerColor = Color(0xFF151515)),
            shape = RoundedCornerShape(12.dp)
        ) {
            Column(
                modifier = Modifier.padding(16.dp),
                verticalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        horizontalArrangement = Arrangement.spacedBy(8.dp)
                    ) {
                        Icon(
                            imageVector = Icons.Default.Terminal,
                            contentDescription = "RouterOS Script Output",
                            tint = Color(0xFF2ECC71)
                        )
                        Text(
                            text = "RouterOS Command Script",
                            style = MaterialTheme.typography.titleSmall,
                            color = Color.White,
                            fontWeight = FontWeight.Bold
                        )
                    }

                    Button(
                        onClick = {
                            val clipboard = context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
                            val clip = ClipData.newPlainText("L2TP Script", generatedScript)
                            clipboard.setPrimaryClip(clip)

                            scriptCopied = true
                            coroutineScope.launch {
                                delay(2000)
                                scriptCopied = false
                            }
                        },
                        colors = ButtonDefaults.buttonColors(
                            containerColor = if (scriptCopied) Color(0xFF2ECC71) else Color(0xFF2C3E50),
                            contentColor = Color.White
                        ),
                        contentPadding = PaddingValues(horizontal = 12.dp, vertical = 6.dp),
                        modifier = Modifier.height(32.dp).testTag("copy_l2tp_script_button")
                    ) {
                        Icon(
                            imageVector = if (scriptCopied) Icons.Default.Check else Icons.Default.ContentCopy,
                            contentDescription = null,
                            modifier = Modifier.size(14.dp)
                        )
                        Spacer(modifier = Modifier.width(4.dp))
                        Text(if (scriptCopied) "Copied!" else "Copy Script", fontSize = 11.sp, fontWeight = FontWeight.Bold)
                    }
                }

                Box(
                    modifier = Modifier
                        .fillMaxWidth()
                        .background(Color(0xFF0F0F0F), shape = RoundedCornerShape(6.dp))
                        .padding(12.dp)
                ) {
                    Text(
                        text = generatedScript,
                        fontFamily = FontFamily.Monospace,
                        fontSize = 11.sp,
                        color = Color(0xFF2ECC71),
                        lineHeight = 16.sp,
                        modifier = Modifier.testTag("l2tp_script_code_text")
                    )
                }
            }
        }

        // Instructions
        Card(
            modifier = Modifier.fillMaxWidth(),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
        ) {
            Column(
                modifier = Modifier.padding(16.dp),
                verticalArrangement = Arrangement.spacedBy(10.dp)
            ) {
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Icon(
                        imageVector = Icons.Default.Info,
                        contentDescription = "Deployment Steps",
                        tint = MaterialTheme.colorScheme.secondary
                    )
                    Text(
                        text = "Deployment & Setup Guide",
                        style = MaterialTheme.typography.titleMedium,
                        fontWeight = FontWeight.Bold,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }

                Divider(color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.1f))

                val steps = listOf(
                    "1. Copy the RouterOS script snippet above.",
                    "2. Open WinBox or WebFig, open a new \"Terminal\" window, paste the script, and hit Enter.",
                    "3. Open your Android Settings -> Network -> VPN.",
                    "4. Add a new VPN profile: \n    • Type: L2TP/IPSec PSK\n    • Server address: [Your Router's Public IP]\n    • IPSec Pre-shared key: $ipsecSecret\n    • Username: $vpnUsername\n    • Password: $vpnPassword",
                    "5. Turn on VPN connection on your device. Once successfully connected, open RouterControl, head to Devices, and add a profile with the Gateway IP: $localAddress.",
                    "6. You're set! Your commands will now run securely over the secure VPN tunnel."
                )

                steps.forEach { step ->
                    Text(
                        text = step,
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                        lineHeight = 20.sp
                    )
                }
            }
        }
    }
}
